#server.port=8888
#spring.application.name=config-client-app
#spring.cloud.config.server.git.uri=https://github.com/RENCHILIU/Spring-Path.git
##spring.cloud.config.server.git.searchPaths='Spring Cloud/Configuring Services Using Distributed Configuration/config-repository'
#spring.cloud.config.server.git.default-label=master #配置文件分支
#spring.cloud.config.server.git.search-paths=config  #配置文件所在根目录
#server:
#  port: 8001
#spring:
#  application:
#    name: cloud-config-server
#  cloud:
#    config:
#      server:
#        git:
#          uri: https://github.com/smltq/spring-boot-demo.git
#          searchPaths: /cloud-config/config-repo/
#          force-pull: true

server:
  port: 8888
spring:
  application:
    name: cloud-config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/RENCHILIU/Spring
          searchPaths: /Spring Cloud/config/
          force-pull: true
          skip-ssl-validation: true
          default-label: main # by default it reads the master branch
